### PR TITLE
fix minor type issue

### PR DESCRIPTION
**Pull request by brandon-pereira**
Fixes https://github.com/didoo/figma-api/issues/46

### CODE REVIEW

**Comment by isaiahtaylor** [comment]
Ran into this issue as well; could this get approved?

**Comment by RWOverdijk** [comment]
@didoo you alive? 😄

**Comment by vgpechenkin** [comment]
@RWOverdijk How about fork this repo?

**Comment by vgpechenkin** [comment]
@RWOverdijk I have also created [PR](https://github.com/didoo/figma-api/pull/48) a few months ago, but It hasn't merged. So I think to create fork.

**Comment by RWOverdijk** [comment]
@vgpechenkin Alright, go for it 😄

**Comment by didoo** [comment]
@brandon-pereira @vgpechenkin @isaiahtaylor @RWOverdijk sorry for the delay, it's merged now I'll release soon (once I merged also the other PRs).

**Comment by didoo** [comment]
Released in [1.11.0](https://www.npmjs.com/package/figma-api/v/1.11.0)

Please @brandon-pereira @vgpechenkin @isaiahtaylor @RWOverdijk let me know if everything is fine.

**Pull request merged**
