### PR TITLE
Correct `style_type` to `styleType`

### PR DESCRIPTION
**Pull request by gossi**
I realized, there is a wrong spelling on one of the types. While the official docs list the type as in your code: https://www.figma.com/developers/api#style-type

The reality shows, that this is incorrect. Here is a snippet from an actual response:

Bildschirmfoto 2021-10-29 um 17 26 27

Also it actually fits the overall naming scheme better tbh (imho) 😅

PS. I also submitted this issue to `support@figma.com`.

### CODE REVIEW

**Comment by didoo** [comment]
@gossi yes, I think they're little by little renaming all the props (without communicating it 🤦‍♂️) to be more consistent. See other PRs already closed.

One question: do you mind you also update the Readme file and "compile" the library via `npm run build`? 
See as reference this PR: https://github.com/didoo/figma-api/pull/22/files
If not, I ca do it.

Thanks for submitting the PR. Once merged, I'll release a new package on npm.

**Comment by gossi** [comment]
Cool, thanks for the hint on what's left. Kept everything in its own commit.

I'm a bit surprised that `npm run build` caused so much changes? Is this all correct?

**Comment by didoo** [comment]
@gossi not sure why there are these changes in the `lib` (generated) files, likely a different package installed. I have run the update as standalone PR, so if you update and merge the upstream `main` in you branch, I would expect to see only your actual changes in your PR.

**Comment by didoo** [comment]
@gossi just released version `1.8.0`. Can you check if works as expected for you? Thanks
https://www.npmjs.com/package/figma-api/v/1.8.0

**Comment by gossi** [comment]
Fantastic! Works like charm, was able to remove all my `// @ts-ignore` comments around them, which makes me very happy.

Thank you for the quick release 😊

**Pull request merged**
