### PR TITLE
Added autolayout v4 properties

### PR DESCRIPTION
**Pull request by vgpechenkin**
Hi. @didoo. 
I added new proprties to autolayout and text.
The official documentation hasn't been updated yet, but I found the PR https://github.com/figma/plugin-typings/pull/132.

### CODE REVIEW

**Comment by vgpechenkin** [comment]
Hi, @didoo. What do you think about this PR?

**Comment by vgpechenkin** [comment]
Hi, @didoo. What do you think about this PR?

**Comment by didoo** [comment]
@vgpechenkin all good for me. I tested it using the APIs on a custom frame, and everything looks fine (not sure how to do otherwise, since documentation is not up to date as usual 🤷‍♂️)

thanks

**Comment by didoo** [comment]
Released in [1.11.0](https://www.npmjs.com/package/figma-api/v/1.11.0)

Please @vgpechenkin let me know if everything is fine.

**Pull request merged**
